// ─────────────────────────────────────────────
//  STOCKS SEO DATA
//  Used by: /analysis/[symbol] programmatic SEO pages
//  Each entry generates one pre-rendered public page
//  targeting "[stock name] AI stock analysis" searches.
// ─────────────────────────────────────────────

export interface SeoStock {
  symbol:      string   // NSE ticker, e.g. RELIANCE
  slug:        string   // URL slug, e.g. reliance-industries
  name:        string   // Full company name
  sector:      string
  cap:         'Large Cap' | 'Mid Cap' | 'Small Cap'
  description: string   // 1–2 sentence SEO description
  keywords:    string[]
  peers:       string[] // slugs of 2–3 related stocks for internal linking
}

export const SEO_STOCKS: SeoStock[] = [
  {
    symbol:      'RELIANCE',
    slug:        'reliance-industries',
    name:        'Reliance Industries',
    sector:      'Conglomerate (Energy, Telecom, Retail)',
    cap:         'Large Cap',
    description: 'Reliance Industries is India\'s largest company by market cap, with major businesses in Jio telecom, Reliance Retail, and petrochemicals. It is one of the most actively traded NSE stocks.',
    keywords:    ['Reliance Industries stock analysis', 'RELIANCE NSE', 'Reliance stock AI prediction', 'best stocks to buy India'],
    peers:       ['hdfc-bank', 'tata-consultancy-services', 'adani-ports'],
  },
  {
    symbol:      'HDFCBANK',
    slug:        'hdfc-bank',
    name:        'HDFC Bank',
    sector:      'Private Banking & Financial Services',
    cap:         'Large Cap',
    description: 'HDFC Bank is India\'s largest private sector bank by assets. It is a benchmark stock for Indian banking sector analysis and one of the highest-weighted NSE Nifty 50 components.',
    keywords:    ['HDFC Bank stock analysis', 'HDFCBANK NSE signal', 'banking stocks India AI', 'best banking stocks India 2026'],
    peers:       ['reliance-industries', 'icici-bank', 'kotak-mahindra-bank'],
  },
  {
    symbol:      'TCS',
    slug:        'tata-consultancy-services',
    name:        'Tata Consultancy Services',
    sector:      'Information Technology',
    cap:         'Large Cap',
    description: 'TCS is India\'s largest IT services company and one of the most consistent dividend-paying large-caps on NSE. Widely tracked by institutional and retail investors globally.',
    keywords:    ['TCS stock analysis', 'TCS NSE signals', 'IT stocks India AI', 'best IT stocks to buy India'],
    peers:       ['infosys', 'wipro', 'hcl-technologies'],
  },
  {
    symbol:      'INFY',
    slug:        'infosys',
    name:        'Infosys',
    sector:      'Information Technology',
    cap:         'Large Cap',
    description: 'Infosys is India\'s second-largest IT exporter. Known for strong deal wins, margin management, and consistent free cash flow — a core holding for most Indian equity portfolios.',
    keywords:    ['Infosys stock analysis', 'INFY NSE prediction', 'Infosys AI signals 2026', 'IT stocks India'],
    peers:       ['tata-consultancy-services', 'wipro', 'hcl-technologies'],
  },
  {
    symbol:      'ICICIBANK',
    slug:        'icici-bank',
    name:        'ICICI Bank',
    sector:      'Private Banking & Financial Services',
    cap:         'Large Cap',
    description: 'ICICI Bank is one of India\'s fastest-growing private sector banks, with a strong retail and SME franchise. A popular NSE stock for both swing and long-term investors.',
    keywords:    ['ICICI Bank stock analysis', 'ICICIBANK NSE', 'banking sector India AI', 'ICICI stock signal'],
    peers:       ['hdfc-bank', 'kotak-mahindra-bank', 'axis-bank'],
  },
  {
    symbol:      'WIPRO',
    slug:        'wipro',
    name:        'Wipro',
    sector:      'Information Technology',
    cap:         'Large Cap',
    description: 'Wipro is a leading Indian IT services and consulting company. It is tracked closely for turnaround signals and deal momentum in the global technology services space.',
    keywords:    ['Wipro stock analysis', 'WIPRO NSE signal', 'IT stocks India 2026', 'Wipro AI prediction'],
    peers:       ['infosys', 'tata-consultancy-services', 'hcl-technologies'],
  },
  {
    symbol:      'HCLTECH',
    slug:        'hcl-technologies',
    name:        'HCL Technologies',
    sector:      'Information Technology',
    cap:         'Large Cap',
    description: 'HCL Technologies is one of India\'s top IT exporters with a strong engineering services and products mix. Frequently analysed for its superior dividend yield relative to IT peers.',
    keywords:    ['HCL Tech stock analysis', 'HCLTECH NSE', 'best IT stocks India', 'HCL Technologies signal'],
    peers:       ['infosys', 'wipro', 'tata-consultancy-services'],
  },
  {
    symbol:      'KOTAKBANK',
    slug:        'kotak-mahindra-bank',
    name:        'Kotak Mahindra Bank',
    sector:      'Private Banking & Financial Services',
    cap:         'Large Cap',
    description: 'Kotak Mahindra Bank is known for its high-quality loan book, strong capital ratios, and consistent return on equity. A favoured stock among quality-focused Indian investors.',
    keywords:    ['Kotak Bank stock analysis', 'KOTAKBANK NSE', 'banking stocks India AI', 'Kotak stock signal 2026'],
    peers:       ['hdfc-bank', 'icici-bank', 'axis-bank'],
  },
  {
    symbol:      'AXISBANK',
    slug:        'axis-bank',
    name:        'Axis Bank',
    sector:      'Private Banking & Financial Services',
    cap:         'Large Cap',
    description: 'Axis Bank is India\'s third-largest private bank by assets. Analysts track it closely for NIM trends, credit cost normalisation, and re-rating potential versus HDFC Bank.',
    keywords:    ['Axis Bank stock analysis', 'AXISBANK NSE signal', 'private bank stocks India', 'Axis Bank AI prediction'],
    peers:       ['hdfc-bank', 'icici-bank', 'kotak-mahindra-bank'],
  },
  {
    symbol:      'ADANIPORTS',
    slug:        'adani-ports',
    name:        'Adani Ports & SEZ',
    sector:      'Infrastructure & Logistics',
    cap:         'Large Cap',
    description: 'Adani Ports is India\'s largest commercial port operator and a key beneficiary of India\'s infrastructure buildout. Tracked for cargo volume data and balance sheet improvement.',
    keywords:    ['Adani Ports stock analysis', 'ADANIPORTS NSE', 'infrastructure stocks India', 'Adani Ports signal 2026'],
    peers:       ['reliance-industries', 'tata-consultancy-services', 'hdfc-bank'],
  },
  {
    symbol:      'TATAMOTORS',
    slug:        'tata-motors',
    name:        'Tata Motors',
    sector:      'Automobile & EV',
    cap:         'Large Cap',
    description: 'Tata Motors is India\'s top EV manufacturer and owner of the Jaguar Land Rover brand globally. Highly tracked for its domestic EV market share and JLR turnaround story.',
    keywords:    ['Tata Motors stock analysis', 'TATAMOTORS NSE signal', 'EV stocks India', 'best auto stocks India 2026'],
    peers:       ['maruti-suzuki', 'mahindra-and-mahindra', 'reliance-industries'],
  },
  {
    symbol:      'MARUTI',
    slug:        'maruti-suzuki',
    name:        'Maruti Suzuki',
    sector:      'Automobile',
    cap:         'Large Cap',
    description: 'Maruti Suzuki is India\'s largest passenger car maker with over 40% market share. A defensive auto pick, tracked for monthly sales data, rural demand, and new model pipeline.',
    keywords:    ['Maruti Suzuki stock analysis', 'MARUTI NSE', 'auto stocks India AI', 'best automobile stocks India'],
    peers:       ['tata-motors', 'mahindra-and-mahindra', 'hdfc-bank'],
  },
  {
    symbol:      'M&M',
    slug:        'mahindra-and-mahindra',
    name:        'Mahindra & Mahindra',
    sector:      'Automobile & Farm Equipment',
    cap:         'Large Cap',
    description: 'Mahindra & Mahindra dominates India\'s SUV and tractor markets. It is one of the strongest-performing auto stocks in India over recent years due to its farm equipment upcycle.',
    keywords:    ['Mahindra stock analysis', 'M&M NSE signal', 'SUV stocks India', 'best auto stocks India 2026'],
    peers:       ['tata-motors', 'maruti-suzuki', 'reliance-industries'],
  },
  {
    symbol:      'SUNPHARMA',
    slug:        'sun-pharma',
    name:        'Sun Pharmaceutical',
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: 'Sun Pharma is India\'s largest pharmaceutical company by revenue. It is a quality large-cap tracked for US generic drug pipeline, specialty segment growth, and consistent margins.',
    keywords:    ['Sun Pharma stock analysis', 'SUNPHARMA NSE signal', 'pharma stocks India', 'best pharma stocks India 2026'],
    peers:       ['dr-reddys-laboratories', 'cipla', 'reliance-industries'],
  },
  {
    symbol:      'DRREDDY',
    slug:        'dr-reddys-laboratories',
    name:        "Dr. Reddy's Laboratories",
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: "Dr. Reddy's is one of India's largest pharma exporters with a strong US generics and biosimilars pipeline. Frequently analysed alongside Sun Pharma for sector rotation signals.",
    keywords:    ["Dr Reddy's stock analysis", 'DRREDDY NSE', 'pharma stocks India AI', 'best healthcare stocks India'],
    peers:       ['sun-pharma', 'cipla', 'infosys'],
  },
  {
    symbol:      'CIPLA',
    slug:        'cipla',
    name:        'Cipla',
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: 'Cipla is a leading Indian pharma company with a strong branded generics business in India and the US. Tracked for chronic therapy growth, US filing pipeline, and margin expansion.',
    keywords:    ['Cipla stock analysis', 'CIPLA NSE signal', 'pharma stocks India 2026', 'Cipla AI prediction'],
    peers:       ['sun-pharma', 'dr-reddys-laboratories', 'hdfc-bank'],
  },
  {
    symbol:      'NESTLEIND',
    slug:        'nestle-india',
    name:        'Nestle India',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: "Nestle India is one of India's most consistent compounders — high ROCE, pricing power, and a loyal consumer base. Tracked as a defensive FMCG holding in volatile markets.",
    keywords:    ['Nestle India stock analysis', 'NESTLEIND NSE', 'FMCG stocks India AI', 'defensive stocks India 2026'],
    peers:       ['hindustan-unilever', 'itc', 'reliance-industries'],
  },
  {
    symbol:      'HINDUNILVR',
    slug:        'hindustan-unilever',
    name:        'Hindustan Unilever',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: 'Hindustan Unilever is the largest FMCG company in India by revenue. Analysts track it for rural demand recovery, volume growth, and gross margin trajectory after commodity cycles.',
    keywords:    ['HUL stock analysis', 'HINDUNILVR NSE signal', 'FMCG stocks India', 'Hindustan Unilever AI prediction'],
    peers:       ['nestle-india', 'itc', 'maruti-suzuki'],
  },
  {
    symbol:      'ITC',
    slug:        'itc',
    name:        'ITC',
    sector:      'FMCG & Cigarettes',
    cap:         'Large Cap',
    description: 'ITC is a diversified FMCG and cigarette conglomerate. Popular among income investors for its high dividend yield, and tracked for its FMCG business scaling to full profitability.',
    keywords:    ['ITC stock analysis', 'ITC NSE signal', 'dividend stocks India', 'ITC AI prediction 2026'],
    peers:       ['hindustan-unilever', 'nestle-india', 'hdfc-bank'],
  },
  {
    symbol:      'BAJFINANCE',
    slug:        'bajaj-finance',
    name:        'Bajaj Finance',
    sector:      'NBFC & Financial Services',
    cap:         'Large Cap',
    description: 'Bajaj Finance is India\'s most successful NBFC with best-in-class AUM growth, digital distribution, and asset quality. A high-beta financial stock favoured by growth investors.',
    keywords:    ['Bajaj Finance stock analysis', 'BAJFINANCE NSE signal', 'NBFC stocks India', 'best financial stocks India 2026'],
    peers:       ['hdfc-bank', 'icici-bank', 'kotak-mahindra-bank'],
  },

  // EXPANSION: Information Technology — additional companies
  {
    symbol:      'TECHM',
    slug:        'tech-mahindra',
    name:        'Tech Mahindra',
    sector:      'Information Technology',
    cap:         'Large Cap',
    description: 'Tech Mahindra is a leading IT services company with a strong focus on telecom, engineering, and digital transformation. Widely tracked for deal momentum and margin recovery signals.',
    keywords:    ['Tech Mahindra stock analysis', 'TECHM NSE signal', 'IT stocks India 2026', 'Tech Mahindra AI prediction'],
    peers:       ['tata-consultancy-services', 'infosys', 'wipro'],
  },
  {
    symbol:      'LTIM',
    slug:        'ltimindtree',
    name:        'LTIMindtree',
    sector:      'Information Technology',
    cap:         'Large Cap',
    description: 'LTIMindtree is a merged entity of L&T Infotech and Mindtree, offering data, cloud, and digital services. Tracked for integration synergies, deal wins, and margin trajectory.',
    keywords:    ['LTIMindtree stock analysis', 'LTIM NSE signal', 'IT stocks India', 'LTIMindtree AI prediction 2026'],
    peers:       ['tata-consultancy-services', 'infosys', 'hcl-technologies'],
  },
  {
    symbol:      'PERSISTENT',
    slug:        'persistent-systems',
    name:        'Persistent Systems',
    sector:      'Information Technology',
    cap:         'Mid Cap',
    description: 'Persistent Systems is a fast-growing mid-cap IT company specialising in software product engineering, AI services, and cloud platforms. A top performer in the Indian IT mid-cap space.',
    keywords:    ['Persistent Systems stock analysis', 'PERSISTENT NSE signal', 'mid cap IT stocks India', 'Persistent Systems AI prediction'],
    peers:       ['coforge', 'mphasis', 'ltimindtree'],
  },
  {
    symbol:      'COFORGE',
    slug:        'coforge',
    name:        'Coforge',
    sector:      'Information Technology',
    cap:         'Mid Cap',
    description: 'Coforge is a high-growth mid-cap IT services company focused on banking, financial services, and insurance verticals. Tracked for consistent revenue growth and deal pipeline expansion.',
    keywords:    ['Coforge stock analysis', 'COFORGE NSE signal', 'mid cap IT stocks India', 'Coforge AI prediction 2026'],
    peers:       ['persistent-systems', 'mphasis', 'tech-mahindra'],
  },
  {
    symbol:      'MPHASIS',
    slug:        'mphasis',
    name:        'Mphasis',
    sector:      'Information Technology',
    cap:         'Mid Cap',
    description: 'Mphasis is a technology services company with deep expertise in BFSI and cloud-native platforms. Closely followed for DXC revenue dependency, deal wins, and offshore margin expansion.',
    keywords:    ['Mphasis stock analysis', 'MPHASIS NSE signal', 'IT stocks India 2026', 'Mphasis AI prediction'],
    peers:       ['persistent-systems', 'coforge', 'wipro'],
  },

  // EXPANSION: Banking & Financial Services — additional companies
  {
    symbol:      'SBIN',
    slug:        'state-bank-of-india',
    name:        'State Bank of India',
    sector:      'Public Sector Banking',
    cap:         'Large Cap',
    description: "State Bank of India is India's largest public sector bank by assets and the country's most widely held banking stock. Tracked for NPA recovery, credit growth, and government policy tailwinds.",
    keywords:    ['SBI stock analysis', 'SBIN NSE signal', 'PSU banking stocks India', 'SBI AI prediction 2026'],
    peers:       ['hdfc-bank', 'icici-bank', 'axis-bank'],
  },
  {
    symbol:      'INDUSINDBK',
    slug:        'indusind-bank',
    name:        'IndusInd Bank',
    sector:      'Private Banking & Financial Services',
    cap:         'Large Cap',
    description: "IndusInd Bank is a private sector bank with a strong vehicle finance and consumer banking franchise. Investors track it for microfinance asset quality, NIM resilience, and management transition.",
    keywords:    ['IndusInd Bank stock analysis', 'INDUSINDBK NSE signal', 'private bank stocks India', 'IndusInd Bank AI prediction'],
    peers:       ['axis-bank', 'kotak-mahindra-bank', 'hdfc-bank'],
  },
  {
    symbol:      'BAJAJFINSV',
    slug:        'bajaj-finserv',
    name:        'Bajaj Finserv',
    sector:      'NBFC & Financial Services',
    cap:         'Large Cap',
    description: "Bajaj Finserv is a holding company for Bajaj Finance, Bajaj Allianz General, and Bajaj Allianz Life Insurance. Tracked as a diversified financial services play across lending and insurance in India.",
    keywords:    ['Bajaj Finserv stock analysis', 'BAJAJFINSV NSE signal', 'NBFC stocks India', 'Bajaj Finserv AI prediction 2026'],
    peers:       ['bajaj-finance', 'hdfc-bank', 'icici-bank'],
  },
  {
    symbol:      'HDFCLIFE',
    slug:        'hdfc-life-insurance',
    name:        'HDFC Life Insurance',
    sector:      'Life Insurance',
    cap:         'Large Cap',
    description: "HDFC Life Insurance is one of India's largest private life insurers by premium income. Tracked for VNB margin growth, APE momentum, and structural tailwinds from India's low life insurance penetration.",
    keywords:    ['HDFC Life stock analysis', 'HDFCLIFE NSE signal', 'insurance stocks India', 'HDFC Life AI prediction 2026'],
    peers:       ['sbi-life-insurance', 'hdfc-bank', 'bajaj-finance'],
  },
  {
    symbol:      'SBILIFE',
    slug:        'sbi-life-insurance',
    name:        'SBI Life Insurance',
    sector:      'Life Insurance',
    cap:         'Large Cap',
    description: "SBI Life Insurance is India's largest private life insurer by individual new business premium. Closely tracked for bancassurance channel productivity, renewal premium, and VNB margin trends.",
    keywords:    ['SBI Life stock analysis', 'SBILIFE NSE signal', 'insurance stocks India', 'SBI Life AI prediction 2026'],
    peers:       ['hdfc-life-insurance', 'state-bank-of-india', 'bajaj-finserv'],
  },
  {
    symbol:      'BANDHANBNK',
    slug:        'bandhan-bank',
    name:        'Bandhan Bank',
    sector:      'Private Banking & Financial Services',
    cap:         'Mid Cap',
    description: "Bandhan Bank is a private sector bank with roots in microfinance, serving underbanked segments across eastern India. Tracked closely for microfinance stress, collection efficiency, and diversification strategy.",
    keywords:    ['Bandhan Bank stock analysis', 'BANDHANBNK NSE signal', 'mid cap banking stocks India', 'Bandhan Bank AI prediction'],
    peers:       ['indusind-bank', 'federal-bank', 'axis-bank'],
  },
  {
    symbol:      'FEDERALBNK',
    slug:        'federal-bank',
    name:        'Federal Bank',
    sector:      'Private Banking & Financial Services',
    cap:         'Mid Cap',
    description: "Federal Bank is a Kerala-based private sector bank with a strong NRI and SME franchise. Analysts track it for credit growth, NIM stability, and its strategic fintech partnerships.",
    keywords:    ['Federal Bank stock analysis', 'FEDERALBNK NSE signal', 'mid cap bank stocks India', 'Federal Bank AI prediction 2026'],
    peers:       ['bandhan-bank', 'indusind-bank', 'kotak-mahindra-bank'],
  },

  // EXPANSION: Pharmaceuticals — additional companies
  {
    symbol:      'DIVISLAB',
    slug:        'divis-laboratories',
    name:        "Divi's Laboratories",
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: "Divi's Laboratories is a leading API and contract manufacturer with a dominant position in select molecules. Tracked for US FDA compliance, custom synthesis ramp-up, and margin recovery.",
    keywords:    ["Divi's Lab stock analysis", 'DIVISLAB NSE signal', 'pharma API stocks India', "Divi's Laboratories AI prediction 2026"],
    peers:       ['sun-pharma', 'dr-reddys-laboratories', 'cipla'],
  },
  {
    symbol:      'AUROPHARMA',
    slug:        'aurobindo-pharma',
    name:        'Aurobindo Pharma',
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: "Aurobindo Pharma is one of India's largest generic drug exporters with a major US and European presence. Tracked for US ANDA pipeline, injectables ramp, and European business margin expansion.",
    keywords:    ['Aurobindo Pharma stock analysis', 'AUROPHARMA NSE signal', 'pharma stocks India AI', 'Aurobindo AI prediction 2026'],
    peers:       ['sun-pharma', 'lupin', 'cipla'],
  },
  {
    symbol:      'LUPIN',
    slug:        'lupin',
    name:        'Lupin',
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: 'Lupin is a global pharmaceutical company with a significant US generics, branded specialty, and India branded business. Investors track it for US complex generics and biosimilars pipeline ramp.',
    keywords:    ['Lupin stock analysis', 'LUPIN NSE signal', 'pharma stocks India 2026', 'Lupin AI prediction'],
    peers:       ['aurobindo-pharma', 'cipla', 'sun-pharma'],
  },
  {
    symbol:      'BIOCON',
    slug:        'biocon',
    name:        'Biocon',
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: "Biocon is India's largest biopharmaceutical company with a global biosimilars portfolio and biologics contract manufacturing via Biocon Biologics. Tracked for biosimilar launches and debt reduction progress.",
    keywords:    ['Biocon stock analysis', 'BIOCON NSE signal', 'biosimilar stocks India', 'Biocon AI prediction 2026'],
    peers:       ['sun-pharma', 'dr-reddys-laboratories', 'cipla'],
  },
  {
    symbol:      'TORNTPHARM',
    slug:        'torrent-pharmaceuticals',
    name:        'Torrent Pharmaceuticals',
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: 'Torrent Pharmaceuticals is a branded generics leader in India, Germany, and Brazil. One of the most consistent pharma compounders, tracked for domestic chronic therapy growth and international expansion.',
    keywords:    ['Torrent Pharma stock analysis', 'TORNTPHARM NSE signal', 'branded generics India', 'Torrent Pharmaceuticals AI prediction'],
    peers:       ['sun-pharma', 'cipla', 'lupin'],
  },
  {
    symbol:      'ALKEM',
    slug:        'alkem-laboratories',
    name:        'Alkem Laboratories',
    sector:      'Pharmaceuticals',
    cap:         'Large Cap',
    description: 'Alkem Laboratories is a domestic-focused pharma company with leadership in anti-infective and gastrointestinal categories. Tracked for India formulations growth, US generics ramp, and margin improvement.',
    keywords:    ['Alkem stock analysis', 'ALKEM NSE signal', 'pharma stocks India', 'Alkem Laboratories AI prediction 2026'],
    peers:       ['torrent-pharmaceuticals', 'lupin', 'cipla'],
  },

  // EXPANSION: Automobiles — additional companies
  {
    symbol:      'BAJAJ-AUTO',
    slug:        'bajaj-auto',
    name:        'Bajaj Auto',
    sector:      'Automobile',
    cap:         'Large Cap',
    description: "Bajaj Auto is the world's largest three-wheeler manufacturer and India's second-largest two-wheeler maker. Tracked for export growth, CNG and EV transition strategy, and premium motorcycle market share.",
    keywords:    ['Bajaj Auto stock analysis', 'BAJAJ-AUTO NSE signal', 'auto stocks India 2026', 'Bajaj Auto AI prediction'],
    peers:       ['hero-motocorp', 'tvs-motor', 'eicher-motors'],
  },
  {
    symbol:      'EICHERMOT',
    slug:        'eicher-motors',
    name:        'Eicher Motors',
    sector:      'Automobile',
    cap:         'Large Cap',
    description: "Eicher Motors is the parent company of Royal Enfield, India's dominant premium motorcycle brand. Investors track it for Royal Enfield volume growth, international expansion, and VECV joint venture profitability.",
    keywords:    ['Eicher Motors stock analysis', 'EICHERMOT NSE signal', 'premium motorcycle stocks India', 'Eicher Motors AI prediction 2026'],
    peers:       ['bajaj-auto', 'hero-motocorp', 'tata-motors'],
  },
  {
    symbol:      'HEROMOTOCO',
    slug:        'hero-motocorp',
    name:        'Hero MotoCorp',
    sector:      'Automobile',
    cap:         'Large Cap',
    description: "Hero MotoCorp is the world's largest two-wheeler manufacturer by volume. Tracked for rural India demand recovery, scooter segment expansion, EV transition roadmap, and export market growth.",
    keywords:    ['Hero MotoCorp stock analysis', 'HEROMOTOCO NSE signal', 'two-wheeler stocks India', 'Hero MotoCorp AI prediction'],
    peers:       ['bajaj-auto', 'eicher-motors', 'tvs-motor'],
  },
  {
    symbol:      'ASHOKLEY',
    slug:        'ashok-leyland',
    name:        'Ashok Leyland',
    sector:      'Automobile',
    cap:         'Large Cap',
    description: "Ashok Leyland is India's second-largest commercial vehicle manufacturer. Closely monitored for CV cycle trends, defence order wins, LCV market share gains, and Switch Mobility EV subsidiary progress.",
    keywords:    ['Ashok Leyland stock analysis', 'ASHOKLEY NSE signal', 'commercial vehicle stocks India', 'Ashok Leyland AI prediction 2026'],
    peers:       ['tata-motors', 'maruti-suzuki', 'bajaj-auto'],
  },
  {
    symbol:      'TVSMOTOR',
    slug:        'tvs-motor',
    name:        'TVS Motor Company',
    sector:      'Automobile',
    cap:         'Large Cap',
    description: 'TVS Motor Company is a leading two-wheeler and three-wheeler manufacturer with a strong premium and EV portfolio. Tracked for iQube EV ramp-up, export growth, and international brand acquisitions.',
    keywords:    ['TVS Motor stock analysis', 'TVSMOTOR NSE signal', 'EV two-wheeler stocks India', 'TVS Motor AI prediction 2026'],
    peers:       ['bajaj-auto', 'hero-motocorp', 'eicher-motors'],
  },

  // EXPANSION: FMCG & Consumer Goods — additional companies
  {
    symbol:      'BRITANNIA',
    slug:        'britannia-industries',
    name:        'Britannia Industries',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: "Britannia Industries is India's largest biscuits and bakery company with dominant brands like Good Day and Marie Gold. Tracked for volume growth recovery, cost savings programme, and new category launches.",
    keywords:    ['Britannia stock analysis', 'BRITANNIA NSE signal', 'FMCG stocks India', 'Britannia Industries AI prediction 2026'],
    peers:       ['hindustan-unilever', 'nestle-india', 'itc'],
  },
  {
    symbol:      'DABUR',
    slug:        'dabur-india',
    name:        'Dabur India',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: "Dabur India is a leading Ayurvedic and natural health products company with global distribution. Closely tracked for rural volume recovery, international business growth, and healthcare category expansion.",
    keywords:    ['Dabur stock analysis', 'DABUR NSE signal', 'FMCG stocks India', 'Dabur India AI prediction 2026'],
    peers:       ['hindustan-unilever', 'marico', 'britannia-industries'],
  },
  {
    symbol:      'MARICO',
    slug:        'marico',
    name:        'Marico',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: "Marico is a leading FMCG company with dominant brands like Parachute and Saffola. Investors track it for coconut oil price cycles, premium foods portfolio growth, and international emerging market expansion.",
    keywords:    ['Marico stock analysis', 'MARICO NSE signal', 'FMCG stocks India', 'Marico AI prediction 2026'],
    peers:       ['dabur-india', 'hindustan-unilever', 'godrej-consumer-products'],
  },
  {
    symbol:      'GODREJCP',
    slug:        'godrej-consumer-products',
    name:        'Godrej Consumer Products',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: "Godrej Consumer Products is a leading FMCG company with strong positions in household insecticides, hair colour, and personal wash. Tracked for Africa business turnaround and India volume growth.",
    keywords:    ['Godrej Consumer stock analysis', 'GODREJCP NSE signal', 'FMCG stocks India', 'Godrej Consumer AI prediction 2026'],
    peers:       ['marico', 'dabur-india', 'hindustan-unilever'],
  },
  {
    symbol:      'COLPAL',
    slug:        'colgate-palmolive-india',
    name:        'Colgate-Palmolive India',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: "Colgate-Palmolive India is the market leader in oral care with 50%+ toothpaste market share. A high-quality defensive FMCG stock tracked for pricing power, premium product mix upgrades, and volume growth.",
    keywords:    ['Colgate India stock analysis', 'COLPAL NSE signal', 'FMCG stocks India', 'Colgate-Palmolive AI prediction 2026'],
    peers:       ['hindustan-unilever', 'nestle-india', 'dabur-india'],
  },
  {
    symbol:      'TATACONSUM',
    slug:        'tata-consumer-products',
    name:        'Tata Consumer Products',
    sector:      'FMCG',
    cap:         'Large Cap',
    description: "Tata Consumer Products is a fast-growing FMCG platform with brands like Tata Tea, Tata Salt, and NourishCo. Tracked for merger synergies, premiumisation strategy, and distribution network expansion.",
    keywords:    ['Tata Consumer stock analysis', 'TATACONSUM NSE signal', 'FMCG stocks India', 'Tata Consumer Products AI prediction'],
    peers:       ['hindustan-unilever', 'nestle-india', 'britannia-industries'],
  },

  // EXPANSION: Energy & Power — additional companies
  {
    symbol:      'ONGC',
    slug:        'ongc',
    name:        'ONGC',
    sector:      'Oil & Gas (Upstream)',
    cap:         'Large Cap',
    description: "ONGC is India's largest oil and gas exploration and production company, producing over 70% of domestic crude oil. Tracked for Brent crude price correlation, subsidy burden, and KG basin output ramp-up.",
    keywords:    ['ONGC stock analysis', 'ONGC NSE signal', 'oil gas stocks India', 'ONGC AI prediction 2026'],
    peers:       ['reliance-industries', 'bharat-petroleum', 'indian-oil-corporation'],
  },
  {
    symbol:      'IOC',
    slug:        'indian-oil-corporation',
    name:        'Indian Oil Corporation',
    sector:      'Oil & Gas (Downstream)',
    cap:         'Large Cap',
    description: "Indian Oil Corporation is India's largest oil refining and marketing company and a Maharatna PSU. Investors track it for refinery GRM, petrol/diesel price sensitivity, and high dividend yield.",
    keywords:    ['Indian Oil stock analysis', 'IOC NSE signal', 'PSU oil stocks India', 'IOC AI prediction 2026'],
    peers:       ['ongc', 'bharat-petroleum', 'reliance-industries'],
  },
  {
    symbol:      'BPCL',
    slug:        'bharat-petroleum',
    name:        'Bharat Petroleum Corporation',
    sector:      'Oil & Gas (Downstream)',
    cap:         'Large Cap',
    description: "Bharat Petroleum is a Maharatna PSU and one of India's largest fuel retailers with a growing natural gas and petrochemicals presence. Tracked for GRM, marketing margins, and strategic divestment news.",
    keywords:    ['BPCL stock analysis', 'BPCL NSE signal', 'oil stocks India AI', 'Bharat Petroleum AI prediction 2026'],
    peers:       ['ongc', 'indian-oil-corporation', 'reliance-industries'],
  },
  {
    symbol:      'POWERGRID',
    slug:        'power-grid-corporation',
    name:        'Power Grid Corporation',
    sector:      'Power Transmission',
    cap:         'Large Cap',
    description: "Power Grid Corporation is India's dominant electricity transmission company with a regulated, asset-heavy model. Prized by income investors for its high dividend yield, TBCB wins, and energy transition exposure.",
    keywords:    ['Power Grid stock analysis', 'POWERGRID NSE signal', 'power stocks India', 'Power Grid AI prediction 2026'],
    peers:       ['ntpc', 'tata-power', 'coal-india'],
  },
  {
    symbol:      'NTPC',
    slug:        'ntpc',
    name:        'NTPC',
    sector:      'Power Generation',
    cap:         'Large Cap',
    description: "NTPC is India's largest power generating company by installed capacity. Analysts track it for thermal capacity utilisation, renewable energy transition targets, and regulated return visibility.",
    keywords:    ['NTPC stock analysis', 'NTPC NSE signal', 'power stocks India', 'NTPC AI prediction 2026'],
    peers:       ['power-grid-corporation', 'tata-power', 'coal-india'],
  },
  {
    symbol:      'TATAPOWER',
    slug:        'tata-power',
    name:        'Tata Power',
    sector:      'Power Generation',
    cap:         'Large Cap',
    description: "Tata Power is a diversified integrated power company with renewable energy as a key growth driver. Closely tracked for solar EPC order book, renewables capacity addition, and Mundra UMPP resolution.",
    keywords:    ['Tata Power stock analysis', 'TATAPOWER NSE signal', 'renewable energy stocks India', 'Tata Power AI prediction 2026'],
    peers:       ['ntpc', 'power-grid-corporation', 'adani-enterprises'],
  },
  {
    symbol:      'COALINDIA',
    slug:        'coal-india',
    name:        'Coal India',
    sector:      'Metals & Mining',
    cap:         'Large Cap',
    description: "Coal India is the world's largest coal mining company and a critical supplier to India's power sector. Tracked for e-auction premiums, production volume targets, high dividend yield, and thermal demand outlook.",
    keywords:    ['Coal India stock analysis', 'COALINDIA NSE signal', 'PSU stocks India', 'Coal India AI prediction 2026'],
    peers:       ['ntpc', 'power-grid-corporation', 'ongc'],
  },

  // EXPANSION: Telecommunications
  {
    symbol:      'BHARTIARTL',
    slug:        'bharti-airtel',
    name:        'Bharti Airtel',
    sector:      'Telecommunications',
    cap:         'Large Cap',
    description: "Bharti Airtel is India's second-largest telecom operator and a leading provider of broadband, enterprise, and African mobile services. Tracked for ARPU expansion, 5G rollout pace, and B2B cloud services growth.",
    keywords:    ['Bharti Airtel stock analysis', 'BHARTIARTL NSE signal', 'telecom stocks India', 'Airtel AI prediction 2026'],
    peers:       ['reliance-industries', 'hdfc-bank', 'tata-consultancy-services'],
  },

  // EXPANSION: Metals & Mining — additional companies
  {
    symbol:      'TATASTEEL',
    slug:        'tata-steel',
    name:        'Tata Steel',
    sector:      'Metals & Steel',
    cap:         'Large Cap',
    description: "Tata Steel is one of the world's largest steel manufacturers with significant operations in India, Europe, and Southeast Asia. Tracked for global steel price cycles, European restructuring, and India capacity expansion.",
    keywords:    ['Tata Steel stock analysis', 'TATASTEEL NSE signal', 'metal stocks India', 'Tata Steel AI prediction 2026'],
    peers:       ['jsw-steel', 'hindalco-industries', 'vedanta'],
  },
  {
    symbol:      'HINDALCO',
    slug:        'hindalco-industries',
    name:        'Hindalco Industries',
    sector:      'Metals & Mining',
    cap:         'Large Cap',
    description: "Hindalco Industries is India's largest aluminium and copper manufacturer and parent of Novelis, the world's largest aluminium recycler. Tracked for LME aluminium prices, Novelis EBITDA, and capacity expansion.",
    keywords:    ['Hindalco stock analysis', 'HINDALCO NSE signal', 'aluminium stocks India', 'Hindalco AI prediction 2026'],
    peers:       ['tata-steel', 'vedanta', 'jsw-steel'],
  },
  {
    symbol:      'JSWSTEEL',
    slug:        'jsw-steel',
    name:        'JSW Steel',
    sector:      'Metals & Steel',
    cap:         'Large Cap',
    description: "JSW Steel is India's largest private sector steel company with a low-cost, high-quality product mix. Analysts track it for capacity utilisation, realisations, iron ore cost management, and overseas acquisitions.",
    keywords:    ['JSW Steel stock analysis', 'JSWSTEEL NSE signal', 'steel stocks India', 'JSW Steel AI prediction 2026'],
    peers:       ['tata-steel', 'hindalco-industries', 'vedanta'],
  },
  {
    symbol:      'VEDL',
    slug:        'vedanta',
    name:        'Vedanta',
    sector:      'Metals & Mining',
    cap:         'Large Cap',
    description: "Vedanta is a diversified metals and mining conglomerate with operations in zinc, aluminium, oil & gas, and steel. Tracked for commodity price exposure, demerger progress, balance sheet deleveraging, and high dividend yield.",
    keywords:    ['Vedanta stock analysis', 'VEDL NSE signal', 'diversified metals stocks India', 'Vedanta AI prediction 2026'],
    peers:       ['hindalco-industries', 'hindustan-zinc', 'tata-steel'],
  },
  {
    symbol:      'HINDZINC',
    slug:        'hindustan-zinc',
    name:        'Hindustan Zinc',
    sector:      'Metals & Mining',
    cap:         'Large Cap',
    description: "Hindustan Zinc is the world's second-largest integrated zinc-lead producer, majority owned by Vedanta. Prized for its premium EBITDA margins, high dividend yield, and zinc-silver commodity exposure.",
    keywords:    ['Hindustan Zinc stock analysis', 'HINDZINC NSE signal', 'zinc stocks India', 'Hindustan Zinc AI prediction 2026'],
    peers:       ['vedanta', 'hindalco-industries', 'tata-steel'],
  },
  {
    symbol:      'NMDC',
    slug:        'nmdc',
    name:        'NMDC',
    sector:      'Metals & Mining',
    cap:         'Large Cap',
    description: "NMDC is India's largest iron ore producer and a Navratna PSU. Tracked for iron ore production volumes, price realisations, e-auction premiums, and the Nagarnar steel plant commissioning ramp.",
    keywords:    ['NMDC stock analysis', 'NMDC NSE signal', 'iron ore stocks India', 'NMDC AI prediction 2026'],
    peers:       ['tata-steel', 'jsw-steel', 'coal-india'],
  },

  // EXPANSION: Real Estate — additional companies
  {
    symbol:      'DLF',
    slug:        'dlf',
    name:        'DLF Limited',
    sector:      'Real Estate',
    cap:         'Large Cap',
    description: "DLF is India's largest real estate developer by market cap, with a premium residential and commercial portfolio. Tracked for new launch pipeline, rental annuity income from DCCDL, and luxury housing demand trends.",
    keywords:    ['DLF stock analysis', 'DLF NSE signal', 'real estate stocks India', 'DLF AI prediction 2026'],
    peers:       ['godrej-properties', 'oberoi-realty', 'prestige-estates'],
  },
  {
    symbol:      'GODREJPROP',
    slug:        'godrej-properties',
    name:        'Godrej Properties',
    sector:      'Real Estate',
    cap:         'Large Cap',
    description: "Godrej Properties is one of India's largest listed real estate developers, with a presence in Mumbai, Pune, NCR, and Bengaluru. Tracked for pre-sales bookings, land bank acquisitions, and execution track record.",
    keywords:    ['Godrej Properties stock analysis', 'GODREJPROP NSE signal', 'real estate stocks India', 'Godrej Properties AI prediction'],
    peers:       ['dlf', 'oberoi-realty', 'prestige-estates'],
  },
  {
    symbol:      'OBEROIRLTY',
    slug:        'oberoi-realty',
    name:        'Oberoi Realty',
    sector:      'Real Estate',
    cap:         'Large Cap',
    description: "Oberoi Realty is a premium real estate developer focused on Mumbai's luxury and aspirational segments. Investors track it for Borivali Sky City launch momentum, high realisation rates, and annuity income expansion.",
    keywords:    ['Oberoi Realty stock analysis', 'OBEROIRLTY NSE signal', 'luxury real estate stocks India', 'Oberoi Realty AI prediction 2026'],
    peers:       ['dlf', 'godrej-properties', 'prestige-estates'],
  },
  {
    symbol:      'PRESTIGE',
    slug:        'prestige-estates',
    name:        'Prestige Estates Projects',
    sector:      'Real Estate',
    cap:         'Large Cap',
    description: "Prestige Estates is one of South India's largest real estate developers with a strong Bengaluru base and pan-India expansion. Tracked for presales velocity, commercial leasing portfolio, and hospitality segment.",
    keywords:    ['Prestige Estates stock analysis', 'PRESTIGE NSE signal', 'South India real estate stocks', 'Prestige Estates AI prediction'],
    peers:       ['dlf', 'godrej-properties', 'oberoi-realty'],
  },

  // EXPANSION: Infrastructure & Engineering — additional companies
  {
    symbol:      'LT',
    slug:        'larsen-and-toubro',
    name:        'Larsen & Toubro',
    sector:      'Infrastructure & Engineering',
    cap:         'Large Cap',
    description: "Larsen & Toubro is India's largest infrastructure and engineering conglomerate, with businesses spanning construction, defence, hydrocarbons, IT services, and financial services. Tracked for mega order inflows and execution.",
    keywords:    ["L&T stock analysis", 'LT NSE signal', 'infrastructure stocks India', 'Larsen Toubro AI prediction 2026'],
    peers:       ['adani-ports', 'ultratech-cement', 'tata-steel'],
  },
  {
    symbol:      'ULTRACEMCO',
    slug:        'ultratech-cement',
    name:        'UltraTech Cement',
    sector:      'Cement & Infrastructure',
    cap:         'Large Cap',
    description: "UltraTech Cement is India's largest cement manufacturer by installed capacity. Tracked for cement demand cycles, realisation trends, capacity addition timelines, and Kesoram Industries integration synergies.",
    keywords:    ['UltraTech Cement stock analysis', 'ULTRACEMCO NSE signal', 'cement stocks India', 'UltraTech AI prediction 2026'],
    peers:       ['grasim-industries', 'ambuja-cements', 'larsen-and-toubro'],
  },
  {
    symbol:      'GRASIM',
    slug:        'grasim-industries',
    name:        'Grasim Industries',
    sector:      'Cement & Infrastructure',
    cap:         'Large Cap',
    description: "Grasim Industries is a flagship Aditya Birla Group company with interests in cement via UltraTech, VSF, chemicals, and financial services. Tracked for holding discount, paints business launch, and cement sector demand.",
    keywords:    ['Grasim Industries stock analysis', 'GRASIM NSE signal', 'cement conglomerate stocks India', 'Grasim AI prediction 2026'],
    peers:       ['ultratech-cement', 'ambuja-cements', 'hindalco-industries'],
  },
  {
    symbol:      'AMBUJACEM',
    slug:        'ambuja-cements',
    name:        'Ambuja Cements',
    sector:      'Cement & Infrastructure',
    cap:         'Large Cap',
    description: "Ambuja Cements is one of India's top cement companies, now part of the Adani Group following its acquisition. Tracked for capacity expansion roadmap, cost efficiencies, and Adani Group synergy benefits.",
    keywords:    ['Ambuja Cement stock analysis', 'AMBUJACEM NSE signal', 'cement stocks India', 'Ambuja Cements AI prediction 2026'],
    peers:       ['ultratech-cement', 'grasim-industries', 'larsen-and-toubro'],
  },

  // EXPANSION: Healthcare & Hospitals — additional companies
  {
    symbol:      'APOLLOHOSP',
    slug:        'apollo-hospitals',
    name:        'Apollo Hospitals Enterprise',
    sector:      'Healthcare & Hospitals',
    cap:         'Large Cap',
    description: "Apollo Hospitals is India's largest private hospital network and a pioneer in healthcare services, digital health, and pharmacy retail. Tracked for EBITDA per occupied bed, Apollo 24/7 digital traction, and expansion.",
    keywords:    ['Apollo Hospitals stock analysis', 'APOLLOHOSP NSE signal', 'hospital stocks India', 'Apollo Hospitals AI prediction 2026'],
    peers:       ['max-healthcare', 'sun-pharma', 'cipla'],
  },
  {
    symbol:      'MAXHEALTH',
    slug:        'max-healthcare',
    name:        'Max Healthcare Institute',
    sector:      'Healthcare & Hospitals',
    cap:         'Large Cap',
    description: "Max Healthcare is one of India's largest hospital networks with a strong presence in North India. Analysts track it for same-hospital revenue growth, occupancy rates, new hospital additions, and margin expansion.",
    keywords:    ['Max Healthcare stock analysis', 'MAXHEALTH NSE signal', 'hospital stocks India', 'Max Healthcare AI prediction 2026'],
    peers:       ['apollo-hospitals', 'sun-pharma', 'dr-reddys-laboratories'],
  },

  // EXPANSION: Consumer Discretionary — additional companies
  {
    symbol:      'TITAN',
    slug:        'titan-company',
    name:        'Titan Company',
    sector:      'Consumer Discretionary',
    cap:         'Large Cap',
    description: "Titan Company is India's largest jewellery and watch retailer, owned by the Tata Group. Tracked for jewellery same-store sales, Tanishq network expansion, Mia growth, and international market ambitions.",
    keywords:    ['Titan stock analysis', 'TITAN NSE signal', 'consumer stocks India', 'Titan Company AI prediction 2026'],
    peers:       ['hindustan-unilever', 'avenue-supermarts', 'trent'],
  },
  {
    symbol:      'DMART',
    slug:        'avenue-supermarts',
    name:        'Avenue Supermarts (D-Mart)',
    sector:      'Consumer Discretionary',
    cap:         'Large Cap',
    description: "Avenue Supermarts operates D-Mart, India's most profitable offline retail chain. Tracked for store addition pace, revenue per square foot, same-store sales growth, and competition from quick-commerce platforms.",
    keywords:    ['D-Mart stock analysis', 'DMART NSE signal', 'retail stocks India', 'Avenue Supermarts AI prediction 2026'],
    peers:       ['titan-company', 'trent', 'hindustan-unilever'],
  },
  {
    symbol:      'TRENT',
    slug:        'trent',
    name:        'Trent',
    sector:      'Consumer Discretionary',
    cap:         'Large Cap',
    description: "Trent is a Tata Group retail company operating Westside, Zudio, and Zara India. One of the fastest-growing retail stocks, tracked for Zudio store additions, revenue per square foot, and premiumisation thesis.",
    keywords:    ['Trent stock analysis', 'TRENT NSE signal', 'retail stocks India', 'Trent AI prediction 2026'],
    peers:       ['titan-company', 'avenue-supermarts', 'hindustan-unilever'],
  },

  // EXPANSION: Conglomerate & Diversified — additional companies
  {
    symbol:      'ADANIENT',
    slug:        'adani-enterprises',
    name:        'Adani Enterprises',
    sector:      'Conglomerate & Infrastructure',
    cap:         'Large Cap',
    description: "Adani Enterprises is the flagship incubation entity of the Adani Group, housing businesses in airports, green hydrogen, solar manufacturing, and data centres. Tracked as a high-beta proxy for India's infrastructure buildout.",
    keywords:    ['Adani Enterprises stock analysis', 'ADANIENT NSE signal', 'infrastructure stocks India', 'Adani Enterprises AI prediction 2026'],
    peers:       ['adani-ports', 'reliance-industries', 'larsen-and-toubro'],
  },
]

export function getStockBySlug(slug: string): SeoStock | undefined {
  return SEO_STOCKS.find((s) => s.slug === slug)
}

export function getPeerStocks(peers: string[]): SeoStock[] {
  return peers
    .map((slug) => getStockBySlug(slug))
    .filter((s): s is SeoStock => s !== undefined)
}
